name = "BioStockholm"
uuid = "eeb925a3-6f9d-43e6-829e-e0ea03b76ecf"
authors = ["Marco Matthies <marco.matthies@gmail.com>"]
version = "0.1.3"

[deps]
Automa = "67c07d97-cdcb-5c2c-af73-a7f9c32a568b"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[compat]
Automa = "0.8"
OrderedCollections = "1"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
